// $Id: installreffile.h,v 1.10 2006/04/28 22:57:21 hvengel Exp $
//  Little cms Profiler 
// Copyright (C) 2005 Hal Engel
//
// THIS SOFTWARE IS PROVIDED "AS-IS" AND WITHOUT WARRANTY OF ANY KIND,
// EXPRESS, IMPLIED OR OTHERWISE, INCLUDING WITHOUT LIMITATION, ANY
// WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
//
// IN NO EVENT SHALL MARTI MARIA BE LIABLE FOR ANY SPECIAL, INCIDENTAL,
// INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND,
// OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
// WHETHER OR NOT ADVISED OF THE POSSIBILITY OF DAMAGE, AND ON ANY THEORY OF
// LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
// OF THIS SOFTWARE.
//
// This file is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
//
// As a special exception to the GNU General Public License, if you
// distribute this file as part of a program that contains a
// configuration script generated by Autoconf, you may include it under
// the same distribution terms that you use for the rest of that program.
//
// Version 1.11

#ifndef INSTALLREFFILE_H
#define INSTALLREFFILE_H

#include <lprofmain.h>
#include <installreffilebase.h>
#include <qurloperator.h>
#include <qtlcmswidgets.h>

class QNetworkOperation;

class InstallRefFile : public InstallRefFileBase
{
    Q_OBJECT
    
public:
    
    InstallRefFile(QWidget *parent = 0);
    ~InstallRefFile();
    
private:
    virtual void slotOK();
    virtual void slotCancel();
    virtual void slotValueChanged();
    virtual void slotHelpButton();
    QUrlOperator urlOp;
    int copyNum;
    
    ref_file_parms dirs;
    targetTemplate files;
    // QAssistantClient* help;

private slots:
   
    void slotFileCopied( QNetworkOperation * );
    
};

#endif
